spring.application.name=archivum
spring.main.web-application-type=none

# Base de datos H2 en archivo
spring.datasource.url=jdbc:h2:file:./data/archivum;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Archivum
app.archivos.ruta=./archivos/documentos
app.backup.ruta=./backups